apiVersion: v1
kind: Namespace
metadata:
  name: keptn-user-interview-2
  annotations:
    keptn.sh/lifecycle-toolkit: "enabled"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-task-2
  namespace: keptn-user-interview-2
  labels:
    app.kubernetes.io/name: nginx-deployment-task-2
    app.kubernetes.io/version: 1.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 5m
              memory: 16Mi
            requests:
              cpu: 1m
              memory: 8Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-task-2
  namespace: keptn-user-interview-2
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
